Map titles = {
  true: {
    "oyna": "Oyna",
    "dil": "EN",
    "takim1": "Takım 1",
    "takim2": "Takım 2",
    "takımAdiGirin": "Takım adını giriniz...",
    "sure": "Süre:",
    "pasHakki": "Pas Hakkı:",
    "tabuCezasi": "Tabu Cezası:",
    "kazanmaSkoru": "Kazanma Skoru:",
    "basla": "Başla",
    "sure_upper": "SÜRE",
    "skor": "SKOR",
    "dogru": "DOĞRU",
    "tabu": "TABU",
    "pas": "PAS",
    "anaMenu": "Ana Menü",
    "devamEt": "Devam Et",
    "ozet": "ÖZET ",
    "yanlis": "YANLIŞ",
    "toplam": "TOPLAM",  },
  false: {
    "oyna": "Play",
    "dil": "TR",
    "takim1": "Team 1",
    "takim2": "Team 2",
    "takımAdiGirin": "Enter team name...",
    "sure": "Time:",
    "pasHakki": "Pass:",
    "tabuCezasi": "Taboo:",
    "kazanmaSkoru": "Win Score:",
    "basla": "Play",
    "sure_upper": "TIME",
    "skor": "SCORE",
    "dogru": "CORRECT",
    "tabu": "TABOO",
    "pas": "PASS",
    "anaMenu": "Main Menu",
    "devamEt": "Continue",
    "ozet": "SUMMARY ",
    "yanlis": "WRONG",
    "toplam": "TOTAL",  }
};